# PersistentVolume (PV) Definition
apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"  # This path is on your Minikube node's filesystem.

---
# PersistentVolumeClaim (PVC) Definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---
# Headless Service Definition
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    run: nginx-sts-demo
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    run: nginx-sts-demo

---
# StatefulSet Definition
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-sts
spec:
  serviceName: nginx-headless
  replicas: 3
  selector:
    matchLabels:
      run: nginx-sts-demo
  template:
    metadata:
      labels:
        run: nginx-sts-demo
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /var/www/
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      storageClassName: manual  # Matching the PVC's storage class
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi
